spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/turismo_tarapoto
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port (Since the Node server was on 3000, we'll keep 3000 so the frontend doesn't need changing)
server.port=3000

# CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
